### ISSUE TITLE
Missing an example with transformers

### ISSUE THREAD

**Issue by nlassaux** [Raschka-research-group/coral_pytorch#35]
I was testing CORN with a default finetuning using the `transformers` library:

```
model = AutoModelForImageClassification.from_pretrained(
    "microsoft/swin-tiny-patch4-window7-224",
    problem_type="multi_label_classification",
    num_labels=len(label2id)-1,
    id2label=id2label,
    label2id=label2id,
    ignore_mismatched_sizes=True,
).to(device)
```

But that raises an issue:

```
ValueError: You passed along `num_labels=3` with an incompatible id to label map: {0: 'unrelevant', 1: 'not happy', 2: 'medium', 3: 'very-happy'}. Since those arguments are inconsistent with each other,  you should remove one of them.
```

It would be nice to have an example using the the syntax to fine-tune used by the library.

**Comment by nlassaux** [comment]
Got it working doing the following:
- `num_labels=len(label2id)-1`
- remove `id2label=id2label` and `label2id=label2id` parameters to avoid issues with transformers validations
- use a CustomTrainer to set our own Loss (CORN in my case)
- add a validation metric with mse and mae, passed to the CustomTrainer

**Comment by rasbt** [comment]
Glad you figured it out. I do have a demo using a model from the transformers library here: 

- https://github.com/Raschka-research-group/coral-pytorch/blob/main/docs/tutorials/pytorch_lightning/distilbert-corn-tripadvisor.md

but I would appreciate more examples of course. In case you can share the code for the above, I'd love to add it to the repo (I'd use a non-proprietary dataset like TripAdvisor above of course)
